{{- if .Values.networkPolicy.enabled }}
{{- $root := . }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "redis-ha.fullname" . }}-network-policy
  namespace: {{ .Release.Namespace | quote }}
{{- if .Values.networkPolicy.annotations }}
  annotations:
    {{- range $key, $value := .Values.networkPolicy.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
  labels:
{{ include "labels.standard" . | indent 4 }}
    {{- range $key, $value := .Values.networkPolicy.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  podSelector:
    matchLabels:
      release: {{ .Release.Name }}
      app: {{ template "redis-ha.name" . }}
  policyTypes:
    - Ingress
    - Egress
  egress:
    - to:
      - podSelector: 
          matchLabels:
            release: {{ .Release.Name }}
            app: {{ template "redis-ha.name" . }}
      ports:
      {{- if ne (int .Values.redis.port) 0 }}
        - port: {{ .Values.redis.port }}
          protocol: TCP
      {{- end }}
      {{- if ne (int .Values.sentinel.port) 0 }}
        - port: {{ .Values.sentinel.port }}
          protocol: TCP
      {{- end }}
      {{- if ne (int .Values.redis.tlsPort) 0 }}
        - port: {{ .Values.redis.tlsPort }}
          protocol: TCP
      {{- end }}
      {{- if ne (int .Values.sentinel.tlsPort) 0 }}
        - port: {{ .Values.sentinel.tlsPort }}
          protocol: TCP
      {{- end }}
{{-  range $rule := .Values.networkPolicy.egressRules }}
    - to:
{{ (tpl (toYaml $rule.selectors) $) | indent 7 }}
      ports:
{{ toYaml $rule.ports | indent 7 }}
{{- end }}
  ingress:
    - from:
      - podSelector:
          matchLabels:
            release: {{ .Release.Name }}
            app: {{ template "redis-ha.name" . }}
      ports: 
      {{- if ne (int .Values.redis.port) 0 }}
        - port: {{ .Values.redis.port }}
          protocol: TCP
      {{- end }}
      {{- if ne (int .Values.sentinel.port) 0 }}
        - port: {{ .Values.sentinel.port }}
          protocol: TCP
      {{- end }}
      {{- if ne (int .Values.redis.tlsPort) 0 }}
        - port: {{ .Values.redis.tlsPort }}
          protocol: TCP
      {{- end }}
      {{- if ne (int .Values.sentinel.tlsPort) 0 }}
        - port: {{ .Values.sentinel.tlsPort }}
          protocol: TCP
      {{- end }}
{{- if .Values.haproxy.enabled }}
    - from:
        - podSelector:
            matchLabels:
              release: {{ .Release.Name }}
              app: {{ template "redis-ha.name" . }}-haproxy
      ports:
      {{- if ne (int .Values.redis.port) 0 }}
        - port: {{ .Values.redis.port }}
          protocol: TCP
      {{- end }}
      {{- if ne (int .Values.sentinel.port) 0 }}
        - port: {{ .Values.sentinel.port }}
          protocol: TCP
      {{- end }}
      {{- if ne (int .Values.redis.tlsPort) 0 }}
        - port: {{ .Values.redis.tlsPort }}
          protocol: TCP
      {{- end }}
      {{- if ne (int .Values.sentinel.tlsPort) 0 }}
        - port: {{ .Values.sentinel.tlsPort }}
          protocol: TCP
      {{- end }}
{{- end }}
{{-  range $rule := .Values.networkPolicy.ingressRules }}
    - from:
{{ (tpl (toYaml $rule.selectors) $) | indent 7 }}
      ports:
{{- if $rule.ports }}
{{ toYaml $rule.ports | indent 7 }}
{{- else }}
      {{- if ne (int .Values.redis.port) 0 }}
        - port: {{ $root.Values.redis.port }}
          protocol: TCP
      {{- end }}
      {{- if ne (int .Values.sentinel.port) 0 }}
        - port: {{ $root.Values.sentinel.port }}
          protocol: TCP
      {{- end }}
      {{- if ne (int .Values.redis.tlsPort) 0 }}
        - port: {{ .Values.redis.tlsPort }}
          protocol: TCP
      {{- end }}
      {{- if ne (int .Values.sentinel.tlsPort) 0 }}
        - port: {{ .Values.sentinel.tlsPort }}
          protocol: TCP
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
